version: "2"
services: 
  web:
    build: ./app
    ports:
      - "3000:8080"
    depends_on:
      - mongodata
    links:
      - mongo
  mongodata:
    depends_on:
      - mongo
    build: .
  mongo:
    image: mongo
    ports:
      - "27017:27017"
